import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const sourcePath = path.join(root, 'src', 'preload', 'preload.cjs');
const contractPath = path.join(root, 'src', 'shared', 'ipc-contracts.cjs');
const outputPath = path.join(root, 'src', 'preload', 'preload-bundled.cjs');

const preloadSource = fs.readFileSync(sourcePath, 'utf8');
const contractSource = fs.readFileSync(contractPath, 'utf8');
const contractRequire = "const { buildPreloadModules } = require('../shared/ipc-contracts.cjs');";

if (!preloadSource.includes(contractRequire)) {
  throw new Error(`Contract import marker not found in ${sourcePath}`);
}

const inlineContract = `const buildPreloadModules = (() => {
  const contractModule = { exports: {} };
  const module = contractModule;
  const exports = contractModule.exports;
${contractSource.split(/\r?\n/).map((line) => `  ${line.trimEnd()}`.trimEnd()).join('\n')}
  return contractModule.exports.buildPreloadModules;
})();`;

const bundledSource = (
  `// AUTO-GENERATED by scripts/build-preload.mjs. Do not edit directly.\n${preloadSource.replace(contractRequire, inlineContract)}`
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .join('\n')
    .trimEnd() + '\n'
);
fs.writeFileSync(outputPath, bundledSource, 'utf8');
console.log(`Generated sandbox-compatible preload: ${path.relative(root, outputPath)}`);
